FROM golang:1.12.1
LABEL maintainer="github@github.com"

RUN apt-get update
RUN apt-get install -y lsb-release
RUN rm -rf /var/lib/apt/lists/*

COPY . /go/src/github.com/pat-addepar/gh-ost
WORKDIR /go/src/github.com/pat-addepar/gh-ost

CMD CGO_ENABLED=0 go test ./go/...
